# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "✗"
use_symbol_for_status = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

# Display hostname
[hostname]
ssh_only = false
format =  "on [$hostname](green) "
trim_at = ".companyname.com"
disabled = false

# Git
